# Generated by Django 5.0 on 2023-12-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SumResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num1", models.IntegerField()),
                ("num2", models.IntegerField()),
                ("result", models.IntegerField()),
            ],
        ),
    ]
